2019-11-03 06:48:17,140 ERROR: Exception on /register [GET] [in /home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ygreneco/flask_app/app/routes.py", line 159, in register
    return render_template('register.html', title='Register', form=form)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ygreneco/flask_app/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ygreneco/flask_app/app/templates/base.html", line 1, in top-level template code
    {% block content %}
  File "/home/ygreneco/flask_app/app/templates/base.html", line 16, in block "content"
    {% block app_content %}
  File "/home/ygreneco/flask_app/app/templates/register.html", line 9, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2019-11-03 07:01:34,329 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 07:15:20,228 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 07:46:44,988 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 08:02:20,934 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 08:36:00,992 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 08:46:18,744 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 09:58:29,173 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 10:33:31,766 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 10:47:37,768 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 11:05:43,847 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 11:22:48,215 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 11:35:29,835 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 11:56:00,689 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 12:50:45,044 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 14:28:09,231 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 14:45:12,068 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 15:07:10,389 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 16:51:40,433 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 17:02:12,653 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 17:41:04,049 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 19:16:18,692 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 19:50:57,501 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 21:30:26,943 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-03 22:58:53,800 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 00:22:48,922 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 01:28:41,264 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 01:54:47,079 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 04:43:54,488 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 05:29:02,398 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 06:20:07,446 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 07:41:27,359 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 07:47:17,216 ERROR: Exception on /register [GET] [in /home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ygreneco/flask_app/app/routes.py", line 159, in register
    return render_template('register.html', title='Register', form=form)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ygreneco/flask_app/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ygreneco/flask_app/app/templates/base.html", line 1, in top-level template code
    {% block content %}
  File "/home/ygreneco/flask_app/app/templates/base.html", line 16, in block "content"
    {% block app_content %}
  File "/home/ygreneco/flask_app/app/templates/register.html", line 9, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2019-11-04 08:18:30,458 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 08:49:35,715 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 09:12:17,437 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 09:30:33,121 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 09:43:48,063 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 10:34:38,803 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 11:27:05,659 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 11:52:12,017 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 12:19:15,808 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 12:52:46,850 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 13:24:18,709 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 14:02:28,581 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-04 14:30:49,676 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
